/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/styles/farble-theme/farbleTheme.ts
 * Command: astryx theme build src/styles/farble-theme/farbleTheme.ts --out src/styles/farble-theme/theme.css
 * Generated: 2026-07-10T00:11:26.847Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}
