/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/styles/farble-theme/farbleTheme.ts
 * Command: astryx theme build src/styles/farble-theme/farbleTheme.ts --out src/styles/farble-theme/theme.css
 * Generated: 2026-07-10T00:11:26.836Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const gothicIconRegistry: IconRegistry;
export declare const farbleTheme: DefinedTheme;
