/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/styles/astryx-theme/neutralTheme.ts
 * Command: astryx theme build src/styles/astryx-theme/neutralTheme.ts --out src/styles/astryx-theme/theme.css
 * Generated: 2026-07-09T00:58:37.837Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface XDSBadgeVariantMap {
    'gray': true;
  }
}
