/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/styles/astryx-theme/neutralTheme.ts
 * Command: astryx theme build src/styles/astryx-theme/neutralTheme.ts --out src/styles/astryx-theme/theme.css
 * Generated: 2026-07-09T00:58:37.830Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const htaitechTheme: DefinedTheme;
